name: tornado_img_workspace
description: "Tornado Image - Monorepo workspace for image encryption app"
version: 1.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

# Workspace dependencies for Melos
dev_dependencies:
  melos: ^6.1.0

